# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Talisman000"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/Te_le_o"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "soundcloud"
name = "SoundCloud"
url = "https://soundcloud.com/talisman000"

[social.params]
icon = "brand-soundcloud"